#! /bin/sh

. "$HOME/.cache/wal/colors.sh"

color1=$(echo "$color1" | sed 's/#//g')
color15=$(echo "$color15" | sed 's/#//g')

berryc save_monitor 0 1
berryc save_monitor 0 2
berryc save_monitor 0 3
berryc save_monitor 0 4
berryc save_monitor 0 5

berryc save_monitor 0 6
berryc save_monitor 0 7
berryc save_monitor 0 8
berryc save_monitor 0 9
berryc save_monitor 0 0

berryc unfocus_color "$color1"
berryc inner_unfocus_color "$color1"
berryc focus_color "$color15"
berryc inner_focus_color "$color15"


berryc border_width 2
berryc inner_border_width 0
berryc pointer_focus
berryc edge_gap 20 0 0 0

berryc smart_place true
berryc edge_lock false
