#! /bin/sh

workingPath=$(dirname $(realpath $0))

. "$HOME/.cache/wal/colors.sh"

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-3 -d 6 7 8 9 10

bspc config normal_border_color "$color1"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width 2
bspc config window_gap 12
bspc config top_padding 20
bspc config single_monocle true
bspc config gapless_monocle true
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
